name: Ansible Setup

on:
    push:
        branches: [main]
        paths: 
            - "ansible/**"
            - ".github/workflows/ansible.yml"
    workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Run Ansible
        run: |
          ansible-playbook \
            -i "${{ secrets.SERVER_HOST }}," \
            -u "${{ secrets.SERVER_USER }}" \
            --private-key ~/.ssh/id_rsa \
            ansible/install-k3s.yml