name: Terraform

on:
  pull_request:
    paths:
      - "terraform/**"

  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:

  plan:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform

      - run: terraform plan
        working-directory: terraform


  apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init
        working-directory: terraform

      - run: terraform apply -auto-approve
        working-directory: terraform